# -*- coding: utf-8 -*-
"""Baseline_SQLNet_Seq2SQL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dCYv7iYAwktO21MZPoeIKjKa2W3qgLP
"""

# !tar -xvjf /content/drive/MyDrive/258/SQLNet/data.tar.bz2

# !pip install --upgrade sqlalchemy
# !pip install --upgrade Babel
!pip install torch torchvision torchaudio
!pip install --upgrade records sqlalchemy Babel

import torch
print(torch.__version__)

if torch.cuda.is_available():
    print("CUDA is available.")
else:
    print("CUDA is not available. Using CPU instead.")

!pwd

cd /content/drive/MyDrive/258/SQLNet

# !pip install -r requirements.txt

# this step downloads glove embedding and unzips it
# If the glove folder is present inside SQLNet and a zip and a text file exists there, this step can be skipped

# !bash download_glove.sh

!python extract_vocab.py

# All the paths and import statements are adjusted according to the current working directory = SQLNet
!python train.py -h

"""## Train a SQLNet model with column attention:"""

# !python train.py --ca

# !python test.py --ca

"""## Train a SQLNet model with column attention and trainable embedding"""

# !python train.py --ca --train_emb

# !python test.py --ca --train_emb

"""## Pretrain a Seq2SQL model on the re-splitted dataset"""

!python train.py --baseline --dataset 1

!python test.py --baseline --dataset 1

"""## Train a Seq2SQL model with Reinforcement Learning after pretraining"""

!python train.py --baseline --dataset 1 --rl

!python test.py --baseline --dataset 1 --rl

